# Generated by Django 5.2.11 on 2026-07-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_googlecalendartoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('institution_admin', 'Institution Admin'), ('registrar', 'Registrar'), ('dvc_academic', 'DVC Academic'), ('dean', 'Dean'), ('hod', 'Head of Department'), ('timetable_officer', 'Timetable Officer'), ('scheduler', 'Scheduler'), ('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
