# Generated by Django 5.2.11 on 2026-06-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPTIMAL', 'Optimal'), ('FEASIBLE', 'Feasible'), ('INFEASIBLE', 'Infeasible'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('solver_score', models.IntegerField(blank=True, help_text='Objective value returned by the solver (lower is better)', null=True)),
                ('solve_time_seconds', models.FloatField(blank=True, null=True)),
                ('courses_scheduled', models.IntegerField(default=0)),
                ('hard_conflicts_found', models.IntegerField(default=0)),
                ('soft_conflicts_found', models.IntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='scheduler.timetable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
