# Generated by Django 5.2.11 on 2026-06-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_add_generation_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this lecturer to a Django user account for login access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('LECTURER_AVAILABILITY', 'Lecturer Availability'), ('ROOM_CAPACITY', 'Room Capacity Check'), ('MAX_CLASSES_PER_DAY', 'Lecturer Max Classes Per Day'), ('NO_EVENING_CLASSES', 'Avoid Evening Classes'), ('ROOM_PREFERENCE', 'Preferred Rooms for Course'), ('LAB_ONLY_COURSE', 'Lab-Only Courses'), ('STUDENT_MAX_CLASSES_PER_DAY', 'Student Group Max Classes Per Day')], max_length=50),
        ),
        migrations.CreateModel(
            name='LecturerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='True = lecturer can teach in this slot; False = unavailable.')),
                ('note', models.CharField(blank=True, help_text="Optional note (e.g. 'Hospital appointment')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduler.lecturer')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_availability', to='scheduler.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Lecturer Availabilities',
                'ordering': ['time_slot__day_of_week', 'time_slot__slot_number'],
                'unique_together': {('lecturer', 'time_slot')},
            },
        ),
    ]
