# Generated by Django 5.2.11 on 2026-06-27 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_lecturer_user_alter_constraint_constraint_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='calendar_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='calendar_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
