# Generated by Django 5.2.11 on 2026-06-27 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_lecturer_calendar_token_studentgroup_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='calendar_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='calendar_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
