# Generated by Django 5.2.11 on 2026-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_lecturer_calendar_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
