# Generated by Django 5.2.11 on 2026-07-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_scheduleslot_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, help_text='Link this group to a parent merged group if they attend classes together.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groups', to='scheduler.studentgroup'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('LECTURER_AVAILABILITY', 'Lecturer Availability'), ('ROOM_CAPACITY', 'Room Capacity Check'), ('MAX_CLASSES_PER_DAY', 'Lecturer Max Classes Per Day'), ('NO_EVENING_CLASSES', 'Avoid Evening Classes'), ('ROOM_PREFERENCE', 'Preferred Rooms for Course'), ('LAB_ONLY_COURSE', 'Lab-Only Courses'), ('STUDENT_MAX_CLASSES_PER_DAY', 'Student Group Max Classes Per Day'), ('LECTURER_MAX_CONSECUTIVE_SLOTS', 'Lecturer Max Consecutive Slots')], max_length=50),
        ),
    ]
