# Generated by Django 5.2.11 on 2026-07-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_studentgroup_parent_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='additional_student_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_courses', to='scheduler.studentgroup'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='max_slots_per_day',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='scheduler.campus')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='scheduler.building'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_features',
            field=models.ManyToManyField(blank=True, related_name='required_by_courses', to='scheduler.roomfeature'),
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='scheduler.roomfeature'),
        ),
        migrations.CreateModel(
            name='BuildingDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walking_time_minutes', models.PositiveIntegerField()),
                ('from_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='scheduler.building')),
                ('to_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='scheduler.building')),
            ],
            options={
                'unique_together': {('from_building', 'to_building')},
            },
        ),
        migrations.CreateModel(
            name='LecturerTimeSlotPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_level', models.CharField(choices=[('prefer', 'Prefer'), ('dislike', 'Dislike')], default='prefer', max_length=10)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_preferences', to='scheduler.lecturer')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot')),
            ],
            options={
                'unique_together': {('lecturer', 'time_slot')},
            },
        ),
    ]
