# Generated by Django 5.2.11 on 2026-07-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_announcement_notification_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture/avatar for the lecturer.', null=True, upload_to='lecturers/avatars/'),
        ),
    ]
