# Generated by Django 5.2.11 on 2026-07-06 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_lecturer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Official staff/employee ID (e.g. EMP/2024/001). Auto-displayed as STAFF-{pk} if blank.', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The actual calendar date of this class session.')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='True while the lecturer has the session open; False after it is closed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='scheduler.scheduleslot')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('schedule_slot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(blank=True, help_text='Optional student registration number for reference.', max_length=50)),
                ('is_present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scheduler.attendancesession')),
            ],
            options={
                'ordering': ['student_name'],
                'unique_together': {('session', 'student_name')},
            },
        ),
    ]
