# Generated by Django 5.2.11 on 2026-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_lecturer_portal_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this lecturer is currently active in the timetabling system.'),
        ),
    ]
