# Generated by Django 6.0.6 on 2026-07-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_lecturer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1, help_text='Academic year (e.g. Year 1, 2, 3)', null=True),
        ),
    ]
