# Generated by Django 6.0.6 on 2026-07-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_studentgroup_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('local_model', models.CharField(max_length=100)),
                ('external_field', models.CharField(max_length=100)),
                ('local_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HOD_REVIEW', 'Head of Department Review'), ('DEAN_REVIEW', 'Dean Review'), ('REGISTRAR_REVIEW', 'Registrar Review'), ('DVC_REVIEW', 'DVC Academic Review'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='scheduler.timetable')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
