# Generated by Django 5.2.11 on 2026-07-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_fieldmapping_timetable_status_approvallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
