# Generated by Django 5.2.11 on 2026-07-10 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_lecturer_email_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('import_type', models.CharField(choices=[('smart', 'Smart Import'), ('manual', 'Manual Import')], default='smart', max_length=20)),
                ('created_count', models.JSONField(default=dict, help_text="{'lecturers': 5, 'rooms': 3, ...}")),
                ('updated_count', models.JSONField(default=dict)),
                ('flagged_dupes', models.JSONField(default=list, help_text='List of {entity_type, incoming, existing, similarity} dicts')),
                ('warnings', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='scheduler.university')),
            ],
            options={
                'verbose_name': 'Import Audit Log',
                'verbose_name_plural': 'Import Audit Logs',
                'ordering': ['-imported_at'],
            },
        ),
    ]
