# Generated by Django 5.2.11 on 2026-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_importauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('LECTURER_AVAILABILITY', 'Lecturer Availability'), ('ROOM_CAPACITY', 'Room Capacity Check'), ('MAX_CLASSES_PER_DAY', 'Lecturer Max Classes Per Day'), ('NO_EVENING_CLASSES', 'Avoid Evening Classes'), ('ROOM_PREFERENCE', 'Preferred Rooms for Course'), ('LAB_ONLY_COURSE', 'Lab-Only Courses'), ('STUDENT_MAX_CLASSES_PER_DAY', 'Student Group Max Classes Per Day'), ('LECTURER_MAX_CONSECUTIVE_SLOTS', 'Lecturer Max Consecutive Slots'), ('CUSTOM_RULE', 'Custom Rule Configuration')], max_length=50),
        ),
    ]
