# Generated by Django 5.2.11 on 2026-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_scheduleslot_double_booking_guard'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='scheduler_s_timetab_e556ee_idx',
            old_name='scheduler_ss_tt_ts_idx',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], default='FT', help_text='Employment contract type: Full-Time (permanent/tenured) or Part-Time (adjunct/sessional).', max_length=2),
        ),
    ]
