# Generated by Django 5.2.11 on 2026-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_add_lecturer_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delivery_mode',
            field=models.CharField(choices=[('PH', 'Physical'), ('OL', 'Online'), ('HY', 'Hybrid')], default='PH', help_text='How this course is delivered: Physical (in-person), Online (virtual/Zoom), or Hybrid.', max_length=2),
        ),
        migrations.AddField(
            model_name='room',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Tick if this is a virtual/online room (Zoom, Teams, Google Meet, etc.). Virtual rooms have no physical location — campus travel rules are skipped.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Lecture', 'Lecture Hall'), ('Lab', 'Laboratory'), ('Seminar', 'Seminar Room'), ('Virtual', 'Virtual / Online Room')], default='Lecture', max_length=50),
        ),
    ]
