# Generated by Django 6.0.7 on 2026-07-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_add_pending_status_to_generationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day_of_week', 'start_time', 'slot_number']},
        ),
        migrations.AddField(
            model_name='lecturer',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates whether this lecturer's information has been verified against institutional records."),
        ),
    ]
